//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.11 at 08:59:57 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.hospital.patient", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.soap.demos.model;
