
package com.soap.ws.client.product;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "productCategoryService", targetNamespace = "http://www.delte.com/products", wsdlLocation = "file:/D:/Practices/java-webservices/soap-ws/jaxb-generate-stubs/jaxb-codehaus-to-java/jaxb-codehaus-jaxws-wsdl-to-java2/src/main/resources/product.wsdl")
public class ProductCategoryService
    extends Service
{

    private final static URL PRODUCTCATEGORYSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTCATEGORYSERVICE_EXCEPTION;
    private final static QName PRODUCTCATEGORYSERVICE_QNAME = new QName("http://www.delte.com/products", "productCategoryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Practices/java-webservices/soap-ws/jaxb-generate-stubs/jaxb-codehaus-to-java/jaxb-codehaus-jaxws-wsdl-to-java2/src/main/resources/product.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTCATEGORYSERVICE_WSDL_LOCATION = url;
        PRODUCTCATEGORYSERVICE_EXCEPTION = e;
    }

    public ProductCategoryService() {
        super(__getWsdlLocation(), PRODUCTCATEGORYSERVICE_QNAME);
    }

    public ProductCategoryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTCATEGORYSERVICE_QNAME, features);
    }

    public ProductCategoryService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTCATEGORYSERVICE_QNAME);
    }

    public ProductCategoryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTCATEGORYSERVICE_QNAME, features);
    }

    public ProductCategoryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductCategoryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductCategoryServicePortType
     */
    @WebEndpoint(name = "productCategoryServicePort")
    public ProductCategoryServicePortType getProductCategoryServicePort() {
        return super.getPort(new QName("http://www.delte.com/products", "productCategoryServicePort"), ProductCategoryServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductCategoryServicePortType
     */
    @WebEndpoint(name = "productCategoryServicePort")
    public ProductCategoryServicePortType getProductCategoryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.delte.com/products", "productCategoryServicePort"), ProductCategoryServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTCATEGORYSERVICE_EXCEPTION!= null) {
            throw PRODUCTCATEGORYSERVICE_EXCEPTION;
        }
        return PRODUCTCATEGORYSERVICE_WSDL_LOCATION;
    }

}
